<a href="https://colab.research.google.com/github/prajwalghule999/Task23/blob/main/Task23(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import joblib
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import files
uploded = files.upload()

In [ ]:
df = "/content/Bank Customer.csv"
df = pd.read_csv(df)
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.drop(["RowNumber","CustomerId","Surname"],axis=1,inplace=True)

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
X = df.drop("Exited",axis=1)

y = df["Exited"]

In [ ]:
X = pd.get_dummies(X,drop_first=True)

In [ ]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False

In [ ]:
columns = X.columns.tolist()

joblib.dump(columns,"columns.pkl")

['columns.pkl']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']

In [ ]:
model = LogisticRegression(random_state=42)

model.fit(X_train,y_train)

LogisticRegression(random_state=42)

In [ ]:
joblib.dump(model,"Logistic_Model.pkl")

['Logistic_Model.pkl']

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1543   64]
 [ 314   79]]

In [ ]:
accuracy = accuracy_score(y_test,y_pred)

print("Accuracy =",accuracy)

Accuracy = 0.811

In [ ]:
recall = recall_score(y_test,y_pred)

print("Recall =",recall)

Recall = 0.2010178117048346

In [ ]:
f1 = f1_score(y_test,y_pred)

print("F1 Score =",f1)

F1 Score = 0.2947761194029851

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

In [ ]:
result = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

result.head(10)

   Actual  Predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       0          0
5       0          0
6       0          0
7       1          0
8       0          0
9       0          0

Q3

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Try different values of K

k_values = [3,5,7]

accuracy_results = {}


for k in k_values:

    knn_model = KNeighborsClassifier(
        n_neighbors=k
    )

    knn_model.fit(
        X_train,
        y_train
    )


    y_pred = knn_model.predict(
        X_test
    )


    accuracy = accuracy_score(
        y_test,
        y_pred
    )


    accuracy_results[k] = accuracy


    print("K =", k)
    print("Accuracy =", accuracy)
    print("---------------------")

K = 3
Accuracy = 0.832
---------------------
K = 5
Accuracy = 0.83
---------------------
K = 7
Accuracy = 0.8345
---------------------

In [ ]:
best_k = max(
    accuracy_results,
    key=accuracy_results.get
)


print("Best K Value =", best_k)

print(
    "Best Accuracy =",
    accuracy_results[best_k]
)

Best K Value = 7
Best Accuracy = 0.8345

In [ ]:
final_knn = KNeighborsClassifier(
    n_neighbors=best_k
)


final_knn.fit(
    X_train,
    y_train
)


y_pred = final_knn.predict(
    X_test
)

In [ ]:
print("Confusion Matrix:")

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)


print("\nAccuracy:",
      accuracy_score(y_test,y_pred))


print("\nPrecision:",
      precision_score(y_test,y_pred))


print("\nRecall:",
      recall_score(y_test,y_pred))


print("\nF1 Score:",
      f1_score(y_test,y_pred))


print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred
    )
)

Confusion Matrix:
[[1524   83]
 [ 248  145]]

Accuracy: 0.8345

Precision: 0.6359649122807017

Recall: 0.36895674300254455

F1 Score: 0.4669887278582931

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      1607
           1       0.64      0.37      0.47       393

    accuracy                           0.83      2000
   macro avg       0.75      0.66      0.68      2000
weighted avg       0.82      0.83      0.82      2000

In [ ]:
joblib.dump(
    final_knn,
    "KNN_Model.pkl"
)

print("KNN Model Saved Successfully")

KNN Model Saved Successfully

Q4

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)


scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
# Create Naive Bayes Model

nb_model = GaussianNB()


# Train Model

nb_model.fit(
    X_train,
    y_train
)

GaussianNB()

In [ ]:
y_pred = nb_model.predict(
    X_test
)

In [ ]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[1526   81]
 [ 252  141]]

In [ ]:
print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred
    )
)

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      1607
           1       0.64      0.36      0.46       393

    accuracy                           0.83      2000
   macro avg       0.75      0.65      0.68      2000
weighted avg       0.81      0.83      0.81      2000

In [ ]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy =", accuracy)

Accuracy = 0.8335

In [ ]:
joblib.dump(
    nb_model,
    "Naive_Bayes_Model.pkl"
)

print("Naive Bayes Model Saved Successfully")

Naive Bayes Model Saved Successfully